version: "4"
services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://mgknn:tst@db:5432/postgres
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "mgknn"
      POSTGRES_PASSWORD: "tst"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: